### PR TITLE
Auto correct port 2375

### PR DESCRIPTION
**Pull request by funkymonkeymonk**
Despite port 2375 being registered to docker, I feel it is worth setting this port to also auto correct in the event that the user is creating more than one instance of boot2docker on their system.

### CODE REVIEW

**Comment by YungSang** [comment]
@funkymonkeymonk
Thank you for the PR.
Excuse me for this late reply. I didn't receive any notify from GitHub about this strangely.

I have considered the same thing several times, but I could not have decided it.

<del>If `auto_correct: true` is set and a user creates more than one instance, the auto assigned port will be `22xx`. I feel that it's not suitable.
And the user has to set `DOCKER_HOST=tcp://localhost:22xx` every time when he wants to switch another boot2docker VM.
(I think `vagrant ssh <vm-id | vm-name>` to log into the VM is much easier than that.
`<vm-id | vm-name>` is from `vagrant global-status`.
You can use `vagrant ssh <vm-id | vm-name> -c "docker version"` in the host as well.)</del>

And also a user may create more than one mistakenly, because it won't exit with a warning message.

What do you think?
Any idea would be appreciated.

**Comment by YungSang** [comment]
FYI:
For that case, the user can use `yungsang/coreos` which has no port-forwarding by default.
PRO: The user can set port-forward as he like. It has the latest and standard kernel instead of tinycore.
CON: The docker in `yungsang/coreos` is not the latest one yet.

**Comment by YungSang** [comment]
@funkymonkeymonk
I'm sorry that my first reply was not good.

My biggest concerns are;
1. <del>It is not easy to handle multiple boot2docker VMs.</del>
2. If there are multiple boot2docker VMs and one of them has the official port forwarding,
it makes a user misuse easily such as deploying a container into an unintended VM.

Do you have any idea to solve the concern?

**Comment by funkymonkeymonk** [comment]
I'll explain my use case. I wanted to create a test cluster. While CoreOS may be designed for this, I will not be using etcd or fleet so it is larger than I need it to be. I also need to be able to create this cluster on machines with minimal specs. This is why I turned to boot2docker.

As for your concerns I definitely see where you are coming from and because of my use case, I didn't need to worry about it. Is there a way to forward the port, but not prevent the user from changing it? For example when I tried to change the port mappings in my Vagrantfile I wasn't able to.

**Comment by YungSang** [comment]
Yes, you are right. CoreOS is bigger than boot2docker.
But once the CoreOS box has been downloaded, the booting time is same.
Its memory is still big though.

```
$ export DOCKER_HOST=tcp://localhost:2375
$ docker version
```

It points always to one VM which has the official port 2375, even at another Vagrantfile folder.
I have experienced misuse once before.

BTW,
Do you have any specific reason to use multiple boot2docker VMs instead of multiple containers in one?

**Comment by YungSang** [comment]
FYI:
You can modify the default vagrantfile in the box directly after downloading.

In Mac OS for example,
`~/.vagrant.d/boxes/yungsang-VAGRANTSLASH-boot2docker/<version>/virtualbox/Vagrantfile`

After modification as your PR, you can create multiple boot2docker VMs as you want.

**Comment by YungSang** [comment]
I realized another way.

You can put `auto_correct: true` to override the default setting as below.

In Vagrantfile at your project folder,

```
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "yungsang/boot2docker"

  config.vm.network :forwarded_port, guest: 2375, host: 2375, auto_correct: true
end

```

**Comment by YungSang** [comment]
@funkymonkeymonk 
How about the above?

If it's OK for you, I would like to keep the default setting without `auto_correct: true`.

**Comment by funkymonkeymonk** [comment]
That's fine.

**Comment by YungSang** [comment]
@funkymonkeymonk 
Thank you so much for letting me find the way to solve this.
I will add this option into the sample Vagrantfile.
https://vagrantcloud.com/yungsang/boot2docker

**Pull request closed without merging**
